---
title: "test"
execute:
  keep-md: true
  echo: false
  warning: false
  message: false
format: pdf
tbl-cap-location: top
---

# APPENDICES {.unnumbered}

```{r}
library(AKaerial)
library(tidyverse)
library(kableExtra)

load("data/YKD_Report.RData")

cap2 = paste0(" indices of indicated breeding birds (grey circles; 2 x [singles + 
              pairs]) and indicated total birds (black circles; 2 x [singles + pairs] 
              + birds in flocks) with 95% confidence intervals (vertical bars from 
              circles), as well as the long-term trend in indicated total birds (black 
              line; 2007–",max(YKGHistoric$combined$Year),") and associated 95% credible 
              intervals (grey band around line) from the Yukon-Kuskokwim Delta Aerial 
              Breeding Population Survey, Alaska, 2007–",max(YKGHistoric$combined$Year),
              ". Years with counts of zero were not included in trend estimates 
              (see Methods for details).")

cap3 <- paste0(" indices of breeding birds (singles + [2 x pairs]) and total birds 
               (singles + [2 x pairs] + birds in flocks) with standard errors (SE) 
               from the Yukon-Kuskokwim Delta Aerial Breeding Population Survey, Alaska, 
               2007-",max(YKGHistoric$combined$Year),".")

cap4 = paste0(" along transects within four physiographic-based strata (high, medium, 
              low, and very high) from the Yukon-Kuskokwim Delta Aerial Breeding 
              Population Survey, Alaska, during the most recent survey year (",
              max(YKGHistoric$combined$Year),")." )

alttext = "A graph of the average index estimate between observers (vertical bars 
from circles), the posterior mean population growth trajectory 1985-2024 (black line), 
and the approximate 95% confidence interval for the trajectory (grey band around line)."

altmap = "A map of species-specific observation locations (black dots) along 
transects within four physiographic-based strata (high, medium, low, and very high) 
of the Arctic Coastal Plain Aerial Breeding Population Survey, Alaska, during the 
most recent survey year (2024)." 
```

## Emperor goose {.unnumbered}

```{r}
#| label: fig-EMGO
#| fig-cap: !expr paste( "Emperor goose", cap2)
#| fig-alt: !expr alttext

sppfig(spp = "EMGO" )
```

{{< pagebreak >}}

### Emperor goose data table {.unnumbered}

```{r}
#| include: true
#| label: tbl-EMGO

kable(EMGO, digits = 0, booktabs = TRUE, linesep = "", longtable=TRUE, format.args = list(big.mark = ","), 
  caption = paste0( "Emperor goose", cap3), align = "lrrrr", 
  col.names = c("Year", "Breeding Birds", "SE", "Total Birds", "SE")) %>%
  kable_styling(font_size=10, position="center")%>%
  row_spec(row = 0, bold = TRUE)

```

{{< pagebreak >}}

### Emperor goose map {.unnumbered}

```{r}
#| label: fig-EMGOmap
#| fig-cap: !expr paste0( "Emperor goose", cap4)
#| fig-alt: A map of species-specific observation locations (black dots) along transects within four physiographic-based strata (high, medium, low, and very high) of the Arctic Coastal Aerial Plain Breeding Population Survey, Alaska, during the most recent survey year (2024). 

AKaerial::ObsMap(area = "YKG", species = "EMGO")

```

{{< pagebreak >}}

